### ISSUE TITLE
IS-Net model never stops processing

### ISSUE THREAD

**Issue by ozgurshn** [john-rocky/CoreML-Models#21]
Hi, thanks for converting IS-Net models to Core ML. As I tried with Xcode 13.4.1 mlmodel preview function, both two models process forever and never return results. Could you please check it?

**Comment by john-rocky** [comment]
Sometimes  xcode preview doesn't work.
Try from code.

**Comment by pboudoin** [comment]
From code it works accordingly, thanks @john-rocky !

**Comment by ozgurshn** [comment]
Thanks it works from code as you say
