### ISSUE TITLE
(Info) I used your script to convert the model and used it in my APP.

### ISSUE THREAD

**Issue by BIGPPWONG** [john-rocky/CoreML-Models#28]
I am writing here to say thanks. I am new to iOS development, and just recently launched my app [PixAI](https://bigppwong.github.io/pixai/ios/2022/12/17/PixAI-Manual.html).   

I used your scripts for `A-ESRGAN` and `MM-RealSR` conversion , the process was very smooth and it saved me a lot of time.

Best regards.

**Comment by john-rocky** [comment]
Thanks for letting me know. I'm glad to hear that my work was useful to you.
May I mention your app somewhere in my repository?

**Comment by BIGPPWONG** [comment]
Yes please. It's my pleasure.
