### ISSUE TITLE
How to set output tensor type as Image Type?

### ISSUE THREAD

**Issue by dragen1860** [john-rocky/CoreML-Models#6]
Dear author:
   I found you can set both the input and output type in Super resolution project to Image type in coreml. Thus it could use preview function in xcode very easily. However, I can not find any ways to set the output multiarray tensor as image type. The online resouce only give details on how to set input as image type. None of those tell how to set output. Thank you.

**Comment by john-rocky** [comment]
Hi dragen1860.

The way to make output image is like...

```python
import coremltools as ct
from coremltools.proto import FeatureTypes_pb2 as ft
mlmodel = ct.models.MLModel("realesrgan.mlmodel")
spec = mlmodel.get_spec()


```

**Comment by hholtmann** [comment]
Just getting into converting models to coreml and I am also having a question/issue regarding my custom conversion script for Real ESRGAN. I understand that the output needs an activation layer and your example was great help. I am however unsure regarding the image input. Does it also need a normalisation of values from -1 to 1? I tried with scale of 1/127.5 and bias values of -1 but it gives wrong results. Also tried with a scale of 1/255 and bias of 0, but the image looks washed out. Any hints?
